[project]
name = "e-commerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Praise Nwankwo", email = "nwankwopraison@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "pydantic>=2.13.4",
]

[project.scripts]
e-commerce = "e_commerce:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
